#! /bin/bash

k=1

for seek in QP HP SP DP;
do
	for qw in 1 2 4;  
	do
	
	touch cpu$k.slurm
	echo "#! /bin/bash " >> cpu$k.slurm

	echo " " >> cpu$k.slurm
	echo "#SBATCH --nodes=1" >> cpu$k.slurm
	echo "#SBATCH --output="$seek$qw".out" >> cpu$k.slurm
	echo "#SBATCH --wait-all-nodes=1" >> cpu$k.slurm
	echo " " >> cpu$k.slurm
	echo " echo \$SLURM_JOB_NODELIST" >> cpu$k.slurm

	echo " " >> cpu$k.slurm
	echo "./MyCPUBench /$(pwd)/cpu_"$seek"_"$qw"thread.dat /$(pwd)/output/cpu_SP_1thread.out.dat" >> cpu$k.slurm
	k=$((k+1))
	done 
done

